{{- range $path, $_  := $.Files.Glob "apps/**/Chart.yaml"}}
{{- $chartName := $path | replace "apps/" "" | replace "/Chart.yaml" ""}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $chartName }}
  namespace: argocd
  annotations:
    {{- if (index $.Values $chartName).helm }}
    helmParametersChecksum: {{ (print (index $.Values $chartName).helm) | sha256sum}}
    {{- end }}
spec:
  project: {{ $.Values.global.projectName}}
  revisionHistoryLimit: 3
  {{- if (index $.Values $chartName).ignoreDifferences }}
  ignoreDifferences:
{{ toYaml (index $.Values $chartName).ignoreDifferences | indent 4 }}
  {{- end }}
  {{- if not (index $.Values $chartName).disableAutoSync }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
          - CreateNamespace=true
  {{- end }}
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $chartName }}
  source:
    repoURL: {{ $.Values.global.source.repoURL }}
    targetRevision: {{ $.Values.global.source.targetRevision }}
    helm:
      valueFiles:
      - values.yaml

---
{{- end }}
